name: Seth D Baron
favicon: null
layout_spectrum: 0.51623
typography_spectrum: 0.05924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4b8aa'
    - '#000000'
    - '#2e3553'
    - '#949695'
    - '#4b6e97'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
